x-default-env: &default-env
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_PORT: ${POSTGRES_PORT:-5432}
  POSTGRES_HOST: db
  APP_ENV: ${APP_ENV:-dev}

x-api-base: &api-base
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - .env
  environment:
    <<: *default-env
    DATABASE_URL: ${DATABASE_URL:-postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT:-5432}/${POSTGRES_DB}}
  depends_on:
    - db

services:
  api:
    <<: *api-base
    profiles: ["prod"]
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "${API_PORT:-8000}:8000"

  api-dev:
    <<: *api-base
    profiles: ["dev"]
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./:/app:cached

  db:
    profiles: ["dev", "prod"]
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_HOST_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


