"""add user platform role

Revision ID: 374c7df54383
Revises: dc6a2788d2e2
Create Date: 2025-08-11 16:46:24.770356+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '374c7df54383'
down_revision: Union[str, None] = 'dc6a2788d2e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_platform_role = sa.Enum('buyer', 'seller', name='user_platform_role', create_type=True)
    user_platform_role.create(op.get_bind(), checkfirst=True)

    op.add_column('users', sa.Column('platform_role', user_platform_role, server_default='buyer', nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'platform_role')
    
    # ### end Alembic commands ###
