"""create category model

Revision ID: 71924c17e7f1
Revises: 374c7df54383
Create Date: 2025-08-13 15:35:45.977293+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71924c17e7f1'
down_revision: Union[str, None] = '374c7df54383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gender', sa.Enum('men', 'women', 'unisex', name='category_gender'), server_default='unisex', nullable=False),
    sa.Column('is_for_kids', sa.Boolean(), nullable=False),
    sa.Column('is_main_category', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_parents',
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', 'child_id'),
    sa.UniqueConstraint('parent_id', 'child_id', name='uq_category_parent_child')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_parents')
    op.drop_table('categories')
    # ### end Alembic commands ###
