name: CI

on:
  push:
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: marketplace
          POSTGRES_USER: marketplace
          POSTGRES_PASSWORD: marketplace
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U marketplace -d marketplace"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=12

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL_CI }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Alembic upgrade
        run: alembic upgrade head
      - name: Lint (ruff)
        run: ruff check .
      - name: Format check (black)
        run: black --check .
      - name: Tests
        run: pytest -q
      - name: Docker build
        run: docker build -t marketplace-ci:latest .
